### PR TITLE
Update README.md with customized url

### PR DESCRIPTION
**Pull request by ys838**

### CODE REVIEW

**Comment by amfleming** [comment]
Hi! Please resolve conflicts

**Comment by ys838** [comment]
Hi, I think I've taken care of it!

**Review by amfleming — CHANGES_REQUESTED** [review]
Too many changes - only change your own url

**Comment by ys838** [comment]
My remote repo has not been updated for a quite of time, so I was not able to just change my own line. Can I close this pull request, and fork the latest repo and resubmit a new pull request?

**Pull request closed without merging**
